/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:96c95320-47ec-49ae-8ebd-303700fd4884",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_QL8ceug0g",
    "aws_user_pools_web_client_id": "12egbe6qsstfm6c6bs01npt8ch",
    "oauth": {
        "domain": "hackduke226c4274-226c4274-dev.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
